extends: ["spectral:oas"]
rules:
  info-contact: warn
  info-license: warn
  oas3-api-servers: error
  operation-tag-defined: error
  operation-operationId: error
  operation-description: warn
  path-params: error
  operation-success-response: error
  oas3-valid-media-example: warn
  typed-enum: error
