-- Phase 16 W4-W8 — drop all participation widget tables.
BEGIN;

DROP TABLE IF EXISTS widget_engagement_counter CASCADE;
DROP TABLE IF EXISTS raise_hand CASCADE;
DROP TABLE IF EXISTS sentiment_vote CASCADE;
DROP TABLE IF EXISTS nav_vote CASCADE;
DROP TABLE IF EXISTS reaction CASCADE;
DROP TABLE IF EXISTS quiz_answer CASCADE;
DROP TABLE IF EXISTS quiz_question CASCADE;
DROP TABLE IF EXISTS quiz CASCADE;
DROP TABLE IF EXISTS qa_submit CASCADE;
DROP TABLE IF EXISTS qa_thread CASCADE;
DROP TABLE IF EXISTS moderation_decision CASCADE;
DROP TABLE IF EXISTS word_cloud_submit CASCADE;
DROP TABLE IF EXISTS word_cloud CASCADE;
DROP TABLE IF EXISTS poll_vote CASCADE;
DROP TABLE IF EXISTS poll CASCADE;

COMMIT;
