###############################################################################
# infra/status-page/main.tf
#
# Status page hosting for status.domio.app.
#
# Strategy: static single-page React app (see infra/status-page/static/) served
# out of S3 behind CloudFront. The page renders components from
# `components.yaml` (source of truth: docs/slos/catalogue.md, regenerated by
# `pnpm --filter @domio/obs-control-plane generate`).
#
# Health checks: a multi-region probe (see infra/synthetics/) hits each
# component's `health_check_url` every 60 s. Failures bubble up to the
# PagerDuty business-hours queue via Alertmanager.
#
# Why this design (vs. Better Stack / Atlassian Statuspage SaaS):
#   - One less vendor; we already pay for CloudFront egress.
#   - The data source (catalogue.md) is in the same monorepo, so drift
#     between "what we promise" and "what we emit" is impossible.
#   - Public status pages are almost always read-only; we don't need SaaS
#     authoring UI. A docs PR suffices.
#
# Why it's safe to do this later: until we hit GA, `status.domio.app` is
# pre-GA and the contract is "best effort". Component creation is driven
# by `components.yaml` so this TF never goes stale.
#
# Out of scope here (deferred to P23+):
#   - Incident timeline UI (today: `p22b.audit-log.md` + Linear timeline)
#   - Subscriber email digest
#   - SSO for "report an issue" button
###############################################################################

terraform {
  required_version = ">= 1.6.0"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.40"
    }
  }

  # Remote state lives in the domio-live account. See infra/bootstrap.
  backend "s3" {
    bucket         = "domio-tf-state"
    key            = "infra/status-page/terraform.tfstate"
    region         = "us-east-1"
    dynamodb_table = "domio-tf-locks"
    encrypt        = true
  }
}

provider "aws" {
  region = var.aws_region
}

variable "aws_region" {
  description = "AWS region for the status page CloudFront/S3."
  type        = string
  default     = "us-east-1"
}

variable "domain_name" {
  description = "Public hostname for the status page."
  type        = string
  default     = "status.domio.app"
}

variable "certificate_arn" {
  description = "ACM certificate ARN for status.domio.app. Must be in us-east-1."
  type        = string
}

variable "alertmanager_webhook_secret_arn" {
  description = "Secrets Manager ARN of the webhook secret used to authenticate component updates posted from the synthetics probe."
  type        = string
}

# ── Static site bucket ────────────────────────────────────────────────────

resource "aws_s3_bucket" "site" {
  bucket = "domio-status-${var.aws_region}"
}

resource "aws_s3_bucket_public_access_block" "site" {
  bucket = aws_s3_bucket.site.id

  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}

resource "aws_s3_bucket_versioning" "site" {
  bucket = aws_s3_bucket.site.id
  versioning_configuration { status = "Enabled" }
}

resource "aws_s3_bucket_server_side_encryption_configuration" "site" {
  bucket = aws_s3_bucket.site.id
  rule {
    apply_server_side_encryption_by_default {
      sse_algorithm = "AES256"
    }
  }
}

# OAC so CloudFront can read private bucket contents.
resource "aws_cloudfront_origin_access_control" "site" {
  name                              = "domio-status-oac"
  origin_access_control_origin_type = "s3"
  signing_behavior                  = "always"
  signing_protocol                  = "sigv4"
}

resource "aws_s3_bucket_policy" "site" {
  bucket = aws_s3_bucket.site.id
  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Sid       = "AllowCloudFrontRead"
      Effect    = "Allow"
      Principal = { Service = "cloudfront.amazonaws.com" }
      Action    = "s3:GetObject"
      Resource  = "${aws_s3_bucket.site.arn}/*"
      Condition = {
        StringEquals = {
          "AWS:SourceArn" = aws_cloudfront_distribution.site.arn
        }
      }
    }]
  })
}

# ── CloudFront distribution ───────────────────────────────────────────────

resource "aws_cloudfront_distribution" "site" {
  enabled             = true
  comment             = "domio status page"
  default_root_object = "index.html"
  price_class         = "PriceClass_100" # US/EU only — fine for a status page

  origin {
    domain_name              = aws_s3_bucket.site.bucket_regional_domain_name
    origin_id                = "domio-status-s3"
    origin_access_control_id = aws_cloudfront_origin_access_control.site.id
  }

  default_cache_behavior {
    target_origin_id       = "domio-status-s3"
    viewer_protocol_policy = "redirect-to-https"
    allowed_methods        = ["GET", "HEAD", "OPTIONS"]
    cached_methods         = ["GET", "HEAD"]
    compress               = true

    # Cache 60 s on the edge — components change on the order of "once a week".
    min_ttl     = 0
    default_ttl = 60
    max_ttl     = 300

    # Forward only the host header; everything else comes from S3.
    forwarded_values {
      query_string = false
      cookies { forward = "none" }
    }
  }

  # Cache-bust on deployments: invalidate /index.html.
  custom_error_response {
    error_code         = 404
    response_code      = 200
    response_page_path = "/index.html"
  }

  restrictions {
    geo_restriction { restriction_type = "none" }
  }

  viewer_certificate {
    acm_certificate_arn      = var.certificate_arn
    ssl_support_method       = "sni-only"
    minimum_protocol_version = "TLSv1.2_2021"
  }

  aliases = [var.domain_name]

  tags = {
    Service = "status-page"
    Owner   = "Platform"
  }
}

# ── Route53 ──────────────────────────────────────────────────────────────

data "aws_route53_zone" "domio" {
  name = "domio.app."
}

resource "aws_route53_record" "apex_alias" {
  zone_id = data.aws_route53_zone.domio.zone_id
  name    = var.domain_name
  type    = "A"

  alias {
    name                   = aws_cloudfront_distribution.site.domain_name
    zone_id                = aws_cloudfront_distribution.site.hosted_zone_id
    evaluate_target_health = false
  }
}

# ── IAM for synthetics probe → Alertmanager webhook ──────────────────────
#
# The synthetics probe (infra/synthetics/) needs to push component updates
# into the status page. It authenticates with the secret below and POSTs
# to https://status.domio.app/api/v1/components which is a small Lambda
# (separate module — out of scope for P22-beta).

data "aws_caller_identity" "current" {}

resource "aws_iam_role_policy" "synthetics_status_page_access" {
  name = "synthetics-status-page-access"
  role = var.synthetics_probe_role_name

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Sid    = "AllowReadWebhookSecret"
      Effect = "Allow"
      Action = ["secretsmanager:GetSecretValue"]
      Resource = var.alertmanager_webhook_secret_arn
    }]
  })
}

# ── Outputs ──────────────────────────────────────────────────────────────

output "distribution_domain" {
  description = "CloudFront domain serving the status page."
  value       = aws_cloudfront_distribution.site.domain_name
}

output "site_bucket" {
  description = "S3 bucket the static site is deployed into."
  value       = aws_s3_bucket.site.bucket
}

output "status_page_url" {
  description = "Public URL of the status page."
  value       = "https://${var.domain_name}"
}
