/**
 * @domio/obs-control-plane — alertmanager routing tests.
 *
 * Verifies:
 *   1. `generateRoutes` produces a route per (tier, severity) bucket.
 *   2. `verifyRoutesCoverAlerts` reports every alert that has no
 *      matching route.
 *   3. `renderAlertmanagerYaml` produces a syntactically valid Alertmanager
 *      YAML body that satisfies our invariants:
 *        - Has a top-level `route:` with at least one child route.
 *        - Has a `receivers:` block listing every receiver used.
 *        - Every route's `receiver` references a defined receiver.
 *   4. For tier-1 page-severity alerts, the route must be the
 *      24/7 PagerDuty primary.
 *   5. For tier-2 page-severity alerts, the route must be the
 *      business-hours PagerDuty.
 *   6. For ticket-severity alerts (any tier), the route is the
 *      low-priority ticket queue.
 *
 * The tests don't pull in a YAML parser — they hand-parse the
 * deterministic output to keep the test surface small.
 */

import { describe, it, expect } from 'vitest';
import {
  generateRoutes,
  verifyRoutesCoverAlerts,
  renderAlertmanagerYaml,
} from './alertmanager.js';
import type { BurnRateAlert, SloEntry } from './types.js';

function slo(overrides: Partial<SloEntry> = {}): SloEntry {
  return {
    service: '@domio/test',
    slo: 'avail-test',
    target: '99.9%',
    targetProbability: 0.999,
    window: '30d',
    windowSeconds: 30 * 86400,
    tier: 'tier-1',
    owner: 'Platform',
    alertPrefix: 'SLOBurnHighTest',
    kind: 'availability',
    ...overrides,
  };
}

function alert(sloIn: SloEntry, severity: 'page' | 'ticket', windowTag = '1h'): BurnRateAlert {
  return {
    alertName: `SLOBurn${severity === 'page' ? 'High' : 'Low'}T${sloIn.tier === 'tier-1' ? 1 : sloIn.tier === 'tier-2' ? 2 : 3}${sloIn.service.replace(/^@domio\//, '').replace(/-/g, '')}${sloIn.slo.replace(/-/g, '')}${windowTag.toUpperCase()}`,
    slo: sloIn,
    severity,
    windowSeconds: windowTag === '1h' ? 3600 : windowTag === '6h' ? 6 * 3600 : windowTag === '24h' ? 24 * 3600 : 72 * 3600,
    windowLabel: windowTag,
    expr: '(some expression)',
    for: '2m',
  };
}

describe('generateRoutes', () => {
  it('emits four routes (one per tier+severity bucket)', () => {
    const routes = generateRoutes([slo()]);
    expect(routes).toHaveLength(4);
  });

  it('tier-1 page → 24/7 PagerDuty primary', () => {
    const routes = generateRoutes([slo()]);
    const t1Page = routes.find(
      (r) => r.matchers.some((m) => m.value === 'tier-1') && r.matchers.some((m) => m.value === 'page'),
    );
    expect(t1Page?.receiver).toBe('pagerduty-platform-primary');
  });

  it('tier-2 page → business-hours PagerDuty', () => {
    const routes = generateRoutes([slo()]);
    const t2Page = routes.find(
      (r) => r.matchers.some((m) => m.value === 'tier-2') && r.matchers.some((m) => m.value === 'page'),
    );
    expect(t2Page?.receiver).toBe('pagerduty-platform-business-hours');
  });

  it('ticket → low-priority ticket queue', () => {
    const routes = generateRoutes([slo()]);
    const ticket = routes.find((r) => r.matchers.some((m) => m.value === 'ticket'));
    expect(ticket?.receiver).toBe('tickets-low-priority');
  });
});

describe('verifyRoutesCoverAlerts', () => {
  it('returns no missing when all alerts match a route', () => {
    const routes = generateRoutes([slo()]);
    const alerts = [
      alert(slo({ tier: 'tier-1' }), 'page'),
      alert(slo({ tier: 'tier-2' }), 'page'),
      alert(slo({ tier: 'tier-3' }), 'page'),
      alert(slo({ tier: 'tier-1' }), 'ticket'),
    ];
    const { missing } = verifyRoutesCoverAlerts(alerts, routes);
    expect(missing).toEqual([]);
  });

  it('reports an unknown-tier alert as missing', () => {
    const routes = generateRoutes([slo()]);
    // A malformed alert whose SLO tier is not tier-1/2/3 has no route.
    const bogus = {
      ...alert(slo({ tier: 'tier-1' }), 'page'),
      slo: slo({ tier: 'tier-1' }),
    };
    // Force-bypass the typed tier to simulate a malformed catalogue row.
    (bogus.slo as unknown as { tier: string }).tier = 'tier-9';
    const { missing } = verifyRoutesCoverAlerts([bogus], routes);
    expect(missing.length).toBeGreaterThan(0);
    expect(missing[0]?.alertName).toBe(bogus.alertName);
  });
});

describe('renderAlertmanagerYaml', () => {
  it('starts with a generated-by comment', () => {
    const yaml = renderAlertmanagerYaml(generateRoutes([slo()]));
    expect(yaml.startsWith('# Auto-generated by @domio/obs-control-plane.')).toBe(true);
  });

  it('contains a top-level `route:` block', () => {
    const yaml = renderAlertmanagerYaml(generateRoutes([slo()]));
    expect(yaml).toMatch(/^route:/m);
  });

  it('lists all receivers in the receivers block', () => {
    const yaml = renderAlertmanagerYaml(generateRoutes([slo()]));
    expect(yaml).toContain('receivers:');
    expect(yaml).toContain('name: pagerduty-platform-primary');
    expect(yaml).toContain('name: pagerduty-platform-business-hours');
    expect(yaml).toContain('name: tickets-low-priority');
  });

  it('every route receiver references a defined receiver', () => {
    const yaml = renderAlertmanagerYaml(generateRoutes([slo()]));
    const receivers = new Set<string>();
    for (const line of yaml.split('\n')) {
      const m = line.match(/^\s*-\s*name:\s*(\S+)/);
      if (m) receivers.add(m[1]!);
    }
    expect(receivers.size).toBeGreaterThan(0);
    for (const r of generateRoutes([slo()])) {
      expect(receivers.has(r.receiver)).toBe(true);
    }
  });

  it('does not have any placeholder receiver names', () => {
    const yaml = renderAlertmanagerYaml(generateRoutes([slo()]));
    expect(yaml).not.toMatch(/TODO/);
    expect(yaml).not.toMatch(/FIXME/);
    expect(yaml).not.toMatch(/XXX/);
  });

  it('uses env-var indirection for secrets (no real keys in source)', () => {
    const yaml = renderAlertmanagerYaml(generateRoutes([slo()]));
    // Must reference $PAGERDUTY_… via env var, never literal keys.
    expect(yaml).toMatch(/service_key:\s*\$PAGERDUTY_/);
    expect(yaml).not.toMatch(/service_key:\s*[A-Za-z0-9]{20,}/);
  });
});
