/**
 * @domio/obs-control-plane — Alertmanager route generation.
 *
 * Generates `infra/alertmanager/routes.yaml` from the SLO catalogue.
 *
 * Routing rules:
 *   - tier-1 + severity=page  → PagerDuty primary + secondary (24/7)
 *   - tier-2/3 + severity=page → PagerDuty business-hours only
 *   - severity=ticket        → ticket queue (becomes next-day backlog)
 */

import type { BurnRateAlert, AlertmanagerRoute, SloEntry } from './types.js';

/** Generate the Alertmanager routes for a list of SLOs. */
export function generateRoutes(_slos: readonly SloEntry[]): AlertmanagerRoute[] {
  const routes: AlertmanagerRoute[] = [];

  // Tier-1 page → 24/7 PagerDuty primary + secondary.
  routes.push({
    matchers: [
      { name: 'tier', value: 'tier-1' },
      { name: 'severity', value: 'page' },
    ],
    receiver: 'pagerduty-platform-primary',
    groupBy: ['alertname', 'slo'],
    groupWait: '30s',
    groupInterval: '5m',
    repeatInterval: '4h',
  });

  // Tier-2 page → business-hours PagerDuty.
  routes.push({
    matchers: [
      { name: 'tier', value: 'tier-2' },
      { name: 'severity', value: 'page' },
    ],
    receiver: 'pagerduty-platform-business-hours',
    groupBy: ['alertname', 'slo'],
    groupWait: '5m',
    groupInterval: '15m',
    repeatInterval: '12h',
  });

  // Tier-3 page → ticket only.
  routes.push({
    matchers: [
      { name: 'tier', value: 'tier-3' },
      { name: 'severity', value: 'page' },
    ],
    receiver: 'tickets-low-priority',
    groupBy: ['alertname'],
    groupWait: '15m',
    groupInterval: '1h',
    repeatInterval: '24h',
  });

  // Severity=ticket always → low-priority ticket queue.
  routes.push({
    matchers: [{ name: 'severity', value: 'ticket' }],
    receiver: 'tickets-low-priority',
    groupBy: ['alertname', 'slo'],
    groupWait: '15m',
    groupInterval: '1h',
    repeatInterval: '24h',
  });

  return routes;
}

/** Verify that every burn-rate alert has a matching Alertmanager route. */
export function verifyRoutesCoverAlerts(
  alerts: readonly BurnRateAlert[],
  routes: readonly AlertmanagerRoute[],
): { missing: BurnRateAlert[] } {
  const missing: BurnRateAlert[] = [];

  for (const alert of alerts) {
    const matched = routes.some((r) =>
      r.matchers.every((m) => {
        if (m.name === 'tier') return m.value === alert.slo.tier;
        if (m.name === 'severity') return m.value === alert.severity;
        return false;
      }),
    );
    if (!matched) missing.push(alert);
  }

  return { missing };
}

/** Render the routes as Alertmanager YAML body. */
export function renderAlertmanagerYaml(routes: readonly AlertmanagerRoute[]): string {
  const out: string[] = ['# Auto-generated by @domio/obs-control-plane.', ''];
  out.push('route:');
  out.push('  receiver: tickets-low-priority');
  out.push('  group_by: [alertname, slo]');
  out.push('  group_wait: 30s');
  out.push('  group_interval: 5m');
  out.push('  repeat_interval: 4h');
  out.push('  routes:');

  for (const r of routes) {
    out.push(...renderRoute(r));
  }

  out.push('');
  out.push('receivers:');
  out.push('  - name: pagerduty-platform-primary');
  out.push('    pagerduty_configs:');
  out.push('      - service_key: $PAGERDUTY_PLATFORM_PRIMARY_KEY');
  out.push('        severity: critical');
  out.push('  - name: pagerduty-platform-business-hours');
  out.push('    pagerduty_configs:');
  out.push('      - service_key: $PAGERDUTY_PLATFORM_BH_KEY');
  out.push('  - name: tickets-low-priority');
  out.push('    webhook_configs:');
  out.push('      - url: $LOW_PRIORITY_TICKETS_WEBHOOK');
  out.push('');

  return out.join('\n');
}

function renderRoute(r: AlertmanagerRoute): string[] {
  const lines: string[] = [];
  lines.push('    - receiver: ' + r.receiver);
  lines.push('      group_by: [' + r.groupBy.map((g) => `"${g}"`).join(', ') + ']');
  lines.push('      group_wait: ' + r.groupWait);
  lines.push('      group_interval: ' + r.groupInterval);
  lines.push('      repeat_interval: ' + r.repeatInterval);
  lines.push('      matchers:');
  for (const m of r.matchers) {
    lines.push(`        - ${m.name} = "${m.value}"`);
  }
  return lines;
}
