/**
 * @domio/obs-control-plane — Prometheus alert generation.
 *
 * Given a list of `SloEntry`, generates the multi-window burn-rate
 * alert rules per `docs/slos/error-budget-policy.md`:
 *
 *   1h @ 14.4×  → page (tier-1) / ticket (tier-2/3)
 *   6h @ 6×     → page (tier-1) / ticket (tier-2/3)
 *   24h @ 3×    → ticket
 *   72h @ 1×    → ticket
 *
 * Output is a Prometheus rules YAML body, ready to drop into
 * `infra/prometheus/alerts/slo.yaml`. The generator is deterministic —
 * given the same input SLOs it produces the same output bytes — so CI
 * can detect drift.
 */

import type { SloEntry, BurnRateAlert } from './types.js';

interface WindowSpec {
  readonly window: '1h' | '6h' | '24h' | '72h';
  readonly burnRateThreshold: number;
  readonly severity: 'page' | 'ticket';
  readonly for_: string;
}

const WINDOW_SPECS: ReadonlyArray<WindowSpec> = [
  { window: '1h', burnRateThreshold: 14.4, severity: 'page', for_: '2m' },
  { window: '6h', burnRateThreshold: 6, severity: 'page', for_: '5m' },
  { window: '24h', burnRateThreshold: 3, severity: 'ticket', for_: '10m' },
  { window: '72h', burnRateThreshold: 1, severity: 'ticket', for_: '30m' },
];

/** Generate burn-rate alerts for one SLO. */
export function generateAlertsForSlo(slo: SloEntry): BurnRateAlert[] {
  return WINDOW_SPECS.map((spec) => ({
    alertName: alertName(slo, spec),
    slo,
    window: spec.window,
    burnRateThreshold: spec.burnRateThreshold,
    severity: tierSeverity(slo.tier, spec.severity),
    for_: spec.for_,
    runbookPath: runbookPath(slo),
  }));
}

/** Generate all burn-rate alerts for a list of SLOs. */
export function generateAllAlerts(slos: readonly SloEntry[]): BurnRateAlert[] {
  return slos.flatMap(generateAlertsForSlo);
}

/** Stable alert name following `docs/slos/error-budget-policy.md`. */
function alertName(slo: SloEntry, spec: WindowSpec): string {
  const t = tierTag(slo.tier);
  const sev = severityTag(spec.severity, spec.window);
  // Strip the package @domio/ prefix and any trailing `-service` suffix,
  // then camelCase so `ai-adapters` becomes `AiAdapters`.
  const serviceShort = slo.service
    .replace(/^@domio\//, '')
    .replace(/-service$/, '')
    .split('-')
    .map((part) => capitalize(part))
    .join('');
  // Append the SLO suffix as a stable token: convert dashes to camelCase.
  const sloSuffix = slo.slo
    .split('-')
    .map((part) => capitalize(part))
    .join('');
  // Window tag (1h, 6h, 24h, 72h) makes every alert name unique.
  const windowTag = capitalize(spec.window);
  return `SLOBurn${sev}${t}${serviceShort}${sloSuffix}${windowTag}`;
}

/** Tier tag for the alert name. */
function tierTag(tier: SloEntry['tier']): string {
  switch (tier) {
    case 'tier-1': return 'T1';
    case 'tier-2': return 'T2';
    case 'tier-3': return 'T3';
  }
}

/** Severity tag from burn rate window. */
function severityTag(baseSeverity: 'page' | 'ticket', window: WindowSpec['window']): string {
  if (baseSeverity === 'page' && window === '1h') return 'High';
  if (baseSeverity === 'page') return 'Med';
  return 'Low';
}

/** Downgrade severity for tier-2 / tier-3 services. */
function tierSeverity(tier: SloEntry['tier'], severity: 'page' | 'ticket'): 'page' | 'ticket' {
  if (tier === 'tier-1') return severity;
  return 'ticket'; // tier-2/3 never page — they ticket.
}

/** Runbook path for an SLO. */
function runbookPath(slo: SloEntry): string {
  return `runbooks/${serviceShort(slo)}/${slo.kind}.md`;
}

/** Service short name (no `@domio/` prefix). */
function serviceShort(slo: SloEntry): string {
  return slo.service.replace(/^@domio\//, '');
}

function capitalize(s: string): string {
  return s.length === 0 ? s : s[0]!.toUpperCase() + s.slice(1);
}

// ---------------------------------------------------------------------------
// Prometheus rule body generation (Prometheus textfile format).
// ---------------------------------------------------------------------------

/** Render the alerts as a Prometheus rules YAML body. */
export function renderPrometheusRules(alerts: readonly BurnRateAlert[]): string {
  const groupedBySlo = groupBy(alerts, (a) => `${a.slo.service}-${a.slo.slo}`);

  const groups = Array.from(groupedBySlo.entries()).map(([key, groupAlerts]) => {
    const slo = groupAlerts[0]!.slo;
    return renderGroup(key, slo, groupAlerts);
  });

  return [
    '# Auto-generated by @domio/obs-control-plane from docs/slos/catalogue.md.',
    '# Do not edit by hand — edit the catalogue and regenerate.',
    '',
    ...groups,
    '',
  ].join('\n');
}

function renderGroup(name: string, slo: SloEntry, alerts: readonly BurnRateAlert[]): string {
  const rules = alerts.map((a) => renderRule(a, slo));
  return [
    '- name: slo-burn-rate-' + name,
    '  rules:',
    ...rules.map((r) => r.split('\n').map((l) => '    ' + l).join('\n')),
  ].join('\n');
}

function renderRule(alert: BurnRateAlert, slo: SloEntry): string {
  const expr = slo.kind === 'availability' ? availExpr(alert, slo) : latExpr(alert, slo);
  return [
    `  - alert: ${alert.alertName}`,
    `    expr: |`,
    `      ${expr}`,
    `    for: ${alert.for_}`,
    '    labels:',
    `      severity: ${alert.severity}`,
    `      slo: ${slo.service}-${slo.slo}`,
    `      tier: ${slo.tier}`,
    '    annotations:',
    `      summary: "${slo.service} ${slo.slo} burning budget at >${alert.burnRateThreshold}× over ${alert.window}"`,
    `      runbook: "${alert.runbookPath}"`,
  ].join('\n');
}

function availExpr(alert: BurnRateAlert, slo: SloEntry): string {
  const serviceShort = slo.service.replace(/^@domio\//, '').replace(/-service$/, '');
  const budget = (1 - slo.targetProbability) * alert.burnRateThreshold;
  return [
    `(`,
    `  sum(rate(http_requests_total{service="${serviceShort}",status=~"5.."}[${alert.window}]))`,
    `  /`,
    `  sum(rate(http_requests_total{service="${serviceShort}"}[${alert.window}]))`,
    `) > ${budget.toFixed(6)}`,
  ].join('\n      ');
}

function latExpr(alert: BurnRateAlert, slo: SloEntry): string {
  const serviceShort = slo.service.replace(/^@domio\//, '').replace(/-service$/, '');
  const threshold = slo.latencyThresholdMs! / 1000; // Prometheus uses seconds
  const budget = (1 - slo.targetProbability) * alert.burnRateThreshold;
  return [
    `(`,
    `  1 - (`,
    `    sum(rate(http_request_duration_seconds_bucket{service="${serviceShort}",le="${threshold}"}[${alert.window}]))`,
    `    /`,
    `    sum(rate(http_request_duration_seconds_count{service="${serviceShort}"}[${alert.window}]))`,
    `  )`,
    `) > ${budget.toFixed(6)}`,
  ].join('\n      ');
}

// ---------------------------------------------------------------------------
// Generic helper.
// ---------------------------------------------------------------------------

function groupBy<T, K>(arr: readonly T[], key: (t: T) => K): Map<K, T[]> {
  const out = new Map<K, T[]>();
  for (const item of arr) {
    const k = key(item);
    const bucket = out.get(k);
    if (bucket) bucket.push(item);
    else out.set(k, [item]);
  }
  return out;
}
