/**
 * @domio/obs-control-plane — status page component generation.
 *
 * Generates `infra/status-page/components.yaml` — one component per
 * service, with health-check URL and a list of SLO names that gate the
 * "operational" status.
 *
 * The status page itself is `status.domio.app` (Atlantis / Better Stack
 * or equivalent). This file is the source-of-truth list of components.
 */

import type { SloEntry, StatusPageComponent } from './types.js';

/** Generate a status-page component per service. */
export function generateStatusPageComponents(
  slos: readonly SloEntry[],
): StatusPageComponent[] {
  const byService = new Map<string, SloEntry[]>();
  for (const slo of slos) {
    const arr = byService.get(slo.service) ?? [];
    arr.push(slo);
    byService.set(slo.service, arr);
  }

  const components: StatusPageComponent[] = [];
  for (const [service, serviceSlos] of byService.entries()) {
    components.push({
      id: componentId(service),
      name: displayName(service),
      description: description(service),
      tier: serviceSlos[0]!.tier,
      healthCheckUrl: `https://${serviceShort(service)}.domio.app/healthz`,
      sloEntries: serviceSlos.map((s) => s.slo),
    });
  }

  // Stable ordering.
  components.sort((a, b) => a.id.localeCompare(b.id));
  return components;
}

/** Render the components as status-page YAML. */
export function renderStatusPageYaml(components: readonly StatusPageComponent[]): string {
  const lines: string[] = ['# Auto-generated by @domio/obs-control-plane.', ''];
  lines.push('components:');
  for (const c of components) {
    lines.push(`  - id: ${c.id}`);
    lines.push(`    name: "${c.name}"`);
    lines.push(`    description: "${c.description}"`);
    lines.push(`    tier: ${c.tier}`);
    lines.push(`    health_check_url: "${c.healthCheckUrl}"`);
    lines.push('    slos:');
    for (const slo of c.sloEntries) {
      lines.push(`      - ${slo}`);
    }
  }
  lines.push('');
  return lines.join('\n');
}

/** Verify that every SLO has a status-page component. */
export function verifyStatusPageCoversSlos(
  components: readonly StatusPageComponent[],
  slos: readonly SloEntry[],
): { missing: SloEntry[] } {
  const serviceSet = new Set(components.map((c) => displayName(c.name)));
  const missing: SloEntry[] = [];
  for (const slo of slos) {
    if (!serviceSet.has(displayName(slo.service))) {
      missing.push(slo);
    }
  }
  return { missing };
}

function componentId(service: string): string {
  return service.replace(/^@domio\//, '').replace(/-/g, '_');
}

function serviceShort(service: string): string {
  return service.replace(/^@domio\//, '');
}

function displayName(service: string): string {
  return service.replace(/^@domio\//, '');
}

function description(service: string): string {
  return `${service.replace(/^@domio\//, '')} — Domio service`;
}
