/**
 * @domio/obs-control-plane — synthetics probe config generation (T-G2.H).
 *
 * Generates `infra/synthetics/probes.yaml` — a multi-region black-box
 * probe plan. One probe per tier-1 component, run every 60s, from three
 * geographic regions (us-east, eu-west, ap-southeast). Probe results
 * flow to Alertmanager via webhook (see
 * `infra/status-page/main.tf`).
 *
 * Why multi-region:
 *   - Single-region probes miss regional DNS / network issues that
 *     only affect some users.
 *   - The status page should not lie about "all operational" if a
 *     region is degraded.
 *
 * Why tier-1 only:
 *   - Tier-1 is the user-facing critical path. We pay the probe cost
 *     for what matters to customers.
 *   - Tier-2/3 are observed via internal SLO burn-rate alerts; no
 *     external probe needed.
 *
 * Out of scope here (P22-beta):
 *   - Latency / synthetic-journey probes (e.g. "open editor, type,
 *     save"). Today we only do the up/down `/healthz` check.
 *   - Probe auth (token rotation, mTLS). Deferred to P23.
 */

import type { SloEntry } from './types.js';

export interface Probe {
  readonly id: string;
  readonly service: string;
  readonly slo: string;
  readonly tier: 'tier-1' | 'tier-2' | 'tier-3';
  readonly url: string;
  readonly regions: readonly string[];
  readonly intervalSeconds: number;
  readonly timeoutSeconds: number;
  readonly expectedStatus: number;
}

const REGIONS = ['us-east-1', 'eu-west-1', 'ap-southeast-1'];

/** Generate probes for tier-1 services only. */
export function generateProbes(slos: readonly SloEntry[]): Probe[] {
  const tier1 = slos.filter((s) => s.tier === 'tier-1');
  return tier1.map((slo) => ({
    id: probeId(slo),
    service: slo.service,
    slo: slo.slo,
    tier: slo.tier,
    url: probeUrl(slo),
    regions: REGIONS,
    intervalSeconds: 60,
    timeoutSeconds: 5,
    expectedStatus: 200,
  }));
}

/** Render probes as YAML. */
export function renderProbesYaml(probes: readonly Probe[]): string {
  const out: string[] = ['# Auto-generated by @domio/obs-control-plane.', ''];
  out.push('probes:');
  for (const p of probes) {
    out.push(`  - id: ${p.id}`);
    out.push(`    service: "${p.service}"`);
    out.push(`    slo: "${p.slo}"`);
    out.push(`    tier: ${p.tier}`);
    out.push(`    url: "${p.url}"`);
    out.push(`    regions: [${p.regions.map((r) => `"${r}"`).join(', ')}]`);
    out.push(`    interval_seconds: ${p.intervalSeconds}`);
    out.push(`    timeout_seconds: ${p.timeoutSeconds}`);
    out.push(`    expected_status: ${p.expectedStatus}`);
  }
  out.push('');
  return out.join('\n');
}

/** Verify probe coverage matches tier-1 catalogue. */
export function verifyProbesCoverTier1(
  probes: readonly Probe[],
  slos: readonly SloEntry[],
): { missing: SloEntry[]; extra: Probe[] } {
  const tier1 = slos.filter((s) => s.tier === 'tier-1');
  const probeKeys = new Set(probes.map((p) => `${p.service}::${p.slo}`));
  const missing = tier1.filter((s) => !probeKeys.has(`${s.service}::${s.slo}`));
  const tier1Keys = new Set(tier1.map((s) => `${s.service}::${s.slo}`));
  const extra = probes.filter((p) => !tier1Keys.has(`${p.service}::${p.slo}`));
  return { missing, extra };
}

function probeId(slo: SloEntry): string {
  const svc = slo.service.replace(/^@domio\//, '').replace(/-service$/, '');
  return `probe-${svc}-${slo.slo}`;
}

function probeUrl(slo: SloEntry): string {
  const svc = slo.service.replace(/^@domio\//, '').replace(/-service$/, '');
  return `https://${svc}.domio.app/healthz`;
}
