/**
 * @domio/obs-control-plane — synthetics tests.
 */

import { describe, it, expect } from 'vitest';
import { generateProbes, renderProbesYaml, verifyProbesCoverTier1 } from './synthetics.js';
import type { SloEntry } from './types.js';

function makeSlo(overrides: Partial<SloEntry> = {}): SloEntry {
  return {
    service: '@domio/example-svc',
    slo: 'avail-example',
    target: '99.9%',
    targetProbability: 0.999,
    window: '30d',
    windowSeconds: 30 * 86400,
    tier: 'tier-1',
    owner: 'Platform',
    alertPrefix: 'SLOBurnHighExample',
    kind: 'availability',
    ...overrides,
  };
}

describe('generateProbes', () => {
  it('emits one probe per tier-1 SLO', () => {
    const probes = generateProbes([
      makeSlo({ service: '@domio/a', slo: 'avail-a' }),
      makeSlo({ service: '@domio/a', slo: 'lat-a-p95', kind: 'latency', target: '< 100 ms' }),
      makeSlo({ service: '@domio/b', slo: 'avail-b', tier: 'tier-2' }),
    ]);
    expect(probes).toHaveLength(2);
    expect(probes.find((p) => p.slo === 'avail-a')).toBeDefined();
    expect(probes.find((p) => p.slo === 'lat-a-p95')).toBeDefined();
  });

  it('uses three regions, 60s interval, 5s timeout', () => {
    const probes = generateProbes([makeSlo()]);
    expect(probes[0]!.regions).toEqual(['us-east-1', 'eu-west-1', 'ap-southeast-1']);
    expect(probes[0]!.intervalSeconds).toBe(60);
    expect(probes[0]!.timeoutSeconds).toBe(5);
  });

  it('probe URL strips @domio/ prefix and -service suffix', () => {
    const probes = generateProbes([makeSlo({ service: '@domio/audience-service' })]);
    expect(probes[0]!.url).toBe('https://audience.domio.app/healthz');
  });

  it('probe id is deterministic', () => {
    const probes = generateProbes([makeSlo({ service: '@domio/realtime-gateway' })]);
    expect(probes[0]!.id).toBe('probe-realtime-gateway-avail-example');
  });
});

describe('renderProbesYaml', () => {
  it('renders valid YAML with header comment', () => {
    const yaml = renderProbesYaml(generateProbes([makeSlo()]));
    expect(yaml.startsWith('# Auto-generated by @domio/obs-control-plane.')).toBe(true);
    expect(yaml).toContain('probes:');
    expect(yaml).toContain('regions: ["us-east-1", "eu-west-1", "ap-southeast-1"]');
    expect(yaml).toContain('interval_seconds: 60');
  });
});

describe('verifyProbesCoverTier1', () => {
  it('reports missing probes', () => {
    const slos = [makeSlo({ slo: 'avail-x' })];
    const result = verifyProbesCoverTier1([], slos);
    expect(result.missing).toHaveLength(1);
    expect(result.extra).toEqual([]);
  });

  it('reports extra probes that do not correspond to tier-1 SLOs', () => {
    const probes = generateProbes([makeSlo({ slo: 'avail-x', tier: 'tier-1' })]);
    // Manually inject an extra probe that is not in the catalogue.
    const extra = [
      ...probes,
      {
        id: 'probe-ghost',
        service: '@domio/ghost',
        slo: 'avail-ghost',
        tier: 'tier-1' as const,
        url: 'https://ghost.domio.app/healthz',
        regions: ['us-east-1'],
        intervalSeconds: 60,
        timeoutSeconds: 5,
        expectedStatus: 200,
      },
    ];
    const result = verifyProbesCoverTier1(extra, [makeSlo({ slo: 'avail-x' })]);
    expect(result.extra).toHaveLength(1);
    expect(result.extra[0]!.service).toBe('@domio/ghost');
  });

  it('passes when probes and tier-1 SLOs are 1:1', () => {
    const slos = [makeSlo({ slo: 'avail-x' })];
    const probes = generateProbes(slos);
    const result = verifyProbesCoverTier1(probes, slos);
    expect(result.missing).toEqual([]);
    expect(result.extra).toEqual([]);
  });
});
