apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.controller.type }}-controller
  labels:
    {{- include "ingress.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
spec:
  replicas: {{ .Values.controller.replicas }}
  selector:
    matchLabels:
      {{- include "ingress.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: controller
  template:
    metadata:
      labels:
        {{- include "ingress.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: controller
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: {{ .Values.securityContext.runAsUser }}
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: controller
          image: "{{ .Values.controller.type }}:{{ .Values.controller.tag }}"
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}