/**
 * @domio/phone-pairing — domain types.
 *
 * A pairing row represents one phone-as-remote device attached to a
 * presenter session. The phone polls/connects over WebRTC data channel
 * (LAN path) or WebSocket (cross-network fallback) and is authenticated
 * by a short-lived signed token (rotated every 60 s). Revoked tokens
 * disconnect within 1 s via the realtime gateway.
 */

export type PairingPlatform = 'ios' | 'android' | 'web' | 'desktop';

export type PairingCapability =
  | 'advance'
  | 'retreat'
  | 'jump'
  | 'laser'
  | 'notes'
  | 'timer'
  | 'parking_lot';

export type PairingStatus = 'active' | 'revoked' | 'expired' | 'disconnected';

export interface PairingTokenClaims {
  /** Session the phone is bound to. */
  session_id: string;
  /** Device id (opaque, generated by the phone on first pairing). */
  device_id: string;
  /** Optional human-readable device label. */
  device_name?: string | undefined;
  /** Rotation epoch — incremented on each token rotation; verifiers reject
   *  any token with a stale epoch. */
  epoch: number;
  /** Issue time (ms since epoch). */
  issued_at_ms: number;
  /** Expiry time (ms since epoch). */
  expires_at_ms: number;
  /** Granted capabilities. */
  capabilities: PairingCapability[];
}

export interface PairingRecord {
  id: string;
  workspace_id: string;
  presenter_session_id: string;
  device_id: string;
  device_name?: string | undefined;
  platform?: PairingPlatform | undefined;
  /** SHA-256 of the active signed token bytes (hex). Used to detect reuse
   *  of an old (rotated) token. */
  token_hash: string;
  token_issued_at_ms: number;
  token_expires_at_ms: number;
  epoch: number;
  capabilities: PairingCapability[];
  status: PairingStatus;
  last_seen_at_ms?: number | undefined;
  revoked_at_ms?: number | undefined;
  revoked_by?: string | undefined;
  created_at_ms: number;
  updated_at_ms: number;
}

export interface MintPairingTokenInput {
  workspace_id: string;
  presenter_session_id: string;
  device_id: string;
  device_name?: string | undefined;
  platform?: PairingPlatform | undefined;
  /** Capabilities to grant. Defaults to the full capability set. */
  capabilities?: PairingCapability[] | undefined;
}

export interface MintedPairingToken {
  /** The opaque signed token bytes. The phone sends this verbatim in the
   *  `Authorization: Bearer <token>` header (or via WebRTC data channel
   *  message header). */
  token: string;
  /** Claims — returned for convenience so the caller can show the QR. */
  claims: PairingTokenClaims;
  /** URL the phone should open after scanning the QR. */
  deep_link: string;
  /** Server rotation epoch — the phone can detect a mismatch. */
  epoch: number;
}

export interface VerifyPairingTokenInput {
  token: string;
  /** Expected session id — verifiers refuse mismatched sessions. */
  session_id: string;
}

export interface VerifyPairingTokenResult {
  ok: boolean;
  claims?: PairingTokenClaims | undefined;
  reason?: string | undefined;
}

// ---------------------------------------------------------------------------
// Errors
// ---------------------------------------------------------------------------

export class PairingError extends Error {
  readonly code: string;
  constructor(code: string, message: string) {
    super(message);
    this.code = code;
    this.name = 'PairingError';
  }
}

export class PairingTokenExpiredError extends PairingError {
  readonly code = 'PAIRING_TOKEN_EXPIRED' as const;
  constructor(message = 'pairing token expired') {
    super('PAIRING_TOKEN_EXPIRED', message);
    this.name = 'PairingTokenExpiredError';
  }
}

export class PairingTokenRevokedError extends PairingError {
  readonly code = 'PAIRING_TOKEN_REVOKED' as const;
  constructor(message = 'pairing token revoked') {
    super('PAIRING_TOKEN_REVOKED', message);
    this.name = 'PairingTokenRevokedError';
  }
}

export class PairingTokenReplayedError extends PairingError {
  readonly code = 'PAIRING_TOKEN_REPLAYED' as const;
  constructor(message = 'pairing token replayed (rotated)') {
    super('PAIRING_TOKEN_REPLAYED', message);
    this.name = 'PairingTokenReplayedError';
  }
}

export class PairingSignatureError extends PairingError {
  readonly code = 'PAIRING_SIGNATURE_INVALID' as const;
  constructor(message = 'pairing token signature invalid') {
    super('PAIRING_SIGNATURE_INVALID', message);
    this.name = 'PairingSignatureError';
  }
}

export class PairingSessionMismatchError extends PairingError {
  readonly code = 'PAIRING_SESSION_MISMATCH' as const;
  constructor(message = 'pairing token bound to a different session') {
    super('PAIRING_SESSION_MISMATCH', message);
    this.name = 'PairingSessionMismatchError';
  }
}

// ---------------------------------------------------------------------------
// Defaults
// ---------------------------------------------------------------------------

export const DEFAULT_PAIRING_CAPABILITIES: readonly PairingCapability[] = [
  'advance',
  'retreat',
  'jump',
  'laser',
  'notes',
  'timer',
  'parking_lot',
] as const;

/** Token rotation interval — 60 s per the phase 15 W6 budget. */
export const PAIRING_ROTATION_MS = 60 * 1000;

/** Hard cap on token lifetime — 5 minutes. After this a phone must re-pair. */
export const PAIRING_MAX_TTL_MS = 5 * 60 * 1000;
