apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: domio-prod
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/environment: prod
spec:
  project: domio
  source:
    repoURL: https://github.com/domio/infrastructure
    targetRevision: HEAD
    path: infrastructure/helm/domio
    helm:
      releaseName: domio
      valueFiles:
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m
