apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: { { include "secrets.fullname" . } }
  labels: { { - include "secrets.labels" . | nindent 4 } }
spec:
  backend:
    vault:
      server: { { .Values.vault.address } }
      path: { { .Values.vault.mountPath } }
      auth:
        kubernetes:
          mountPath: { { .Values.vault.authPath } }
          role: { { .Values.vault.role } }
      refreshInterval: { { .Values.vault.refreshInterval } }
  retrySettings:
    maxRetries: 5
    retryInterval: 10s
