/**
 * Live-analytics — WebSocket fan-out hub (Phase 17 W10).
 *
 * Maintains one subscriber Set per (workspace_id, session_id). On
 * every pulse update from the orchestrator, broadcasts the snapshot
 * to every subscriber. Subscribers are identified by an opaque id
 * (generated by the WS server) and can be removed when the WS
 * connection closes.
 *
 * This is a minimal pub/sub layer designed for the HUD. The graphql-ws
 * endpoint in routes/ws.ts reads from this hub.
 */

import type { LivePulse } from '../types.js';

export type SubscriberId = string;

export interface Hub {
  /** Register a new subscriber for a session. Returns the subscriber id. */
  subscribe(workspace_id: string, session_id: string, push: (pulse: LivePulse) => void): SubscriberId;
  /** Remove a subscriber by id. */
  unsubscribe(workspace_id: string, session_id: string, id: SubscriberId): void;
  /** Send the latest pulse to every subscriber of a session. */
  broadcast(workspace_id: string, session_id: string, pulse: LivePulse): void;
  /** Close the channel — used after a session summary is written. */
  close(workspace_id: string, session_id: string): void;
  /** Total subscribers across all sessions. */
  totalSubscribers(): number;
  /** Subscribers for a single session. */
  subscribersFor(workspace_id: string, session_id: string): number;
}

export function buildHub(): Hub {
  let nextId = 0;
  const channels = new Map<string, Map<SubscriberId, (pulse: LivePulse) => void>>();

  function key(workspace_id: string, session_id: string): string {
    return `${workspace_id}|${session_id}`;
  }

  return {
    subscribe(workspace_id, session_id, push) {
      nextId += 1;
      const id = `sub-${nextId}`;
      const k = key(workspace_id, session_id);
      let channel = channels.get(k);
      if (!channel) {
        channel = new Map();
        channels.set(k, channel);
      }
      channel.set(id, push);
      return id;
    },
    unsubscribe(workspace_id, session_id, id) {
      const channel = channels.get(key(workspace_id, session_id));
      if (!channel) return;
      channel.delete(id);
      if (channel.size === 0) channels.delete(key(workspace_id, session_id));
    },
    broadcast(workspace_id, session_id, pulse) {
      const channel = channels.get(key(workspace_id, session_id));
      if (!channel) return;
      for (const push of channel.values()) {
        try {
          push(pulse);
        } catch {
          // drop errors on a per-subscriber basis; the WS handler
          // will clean up on disconnect.
        }
      }
    },
    close(workspace_id, session_id) {
      const k = key(workspace_id, session_id);
      const channel = channels.get(k);
      if (!channel) return;
      // Send a final pulse to every subscriber so HUD clients can
      // show the "session ended" affordance before the WS closes.
      const finalPulse: LivePulse = {
        workspace_id,
        session_id,
        ts_ms: Date.now(),
        concurrent_viewers: 0,
        current_slide_id: null,
        reaction_count: 0,
        poll_vote_count: 0,
        last_seq: 0,
      };
      for (const push of channel.values()) {
        try {
          push(finalPulse);
        } catch {
          /* ignore */
        }
      }
      channels.delete(k);
    },
    totalSubscribers() {
      let n = 0;
      for (const c of channels.values()) n += c.size;
      return n;
    },
    subscribersFor(workspace_id, session_id) {
      return channels.get(key(workspace_id, session_id))?.size ?? 0;
    },
  };
}