/**
 * Hardcoded metadata for the Plugin SDK portal (Wave 10 §S10.5).
 *
 * The tutorial catalogue and publish-flow steps are static reference data
 * that ships with the landing site. They are surfaced both by the
 * tutorials component and the deeper anchor sections on the page.
 */

export interface PluginTutorial {
  slug: string;
  title: string;
  description: string;
  time_estimate_min: number;
  difficulty: 'beginner' | 'intermediate' | 'advanced';
}

export interface PublishStep {
  step: number;
  title: string;
  description: string;
}

export const TUTORIALS: ReadonlyArray<PluginTutorial> = [
  {
    slug: 'canvas-plugin',
    title: 'Canvas plugin',
    description:
      'Add a custom node type to the Domio canvas — register geometry, controls, and a preview thumbnail.',
    time_estimate_min: 15,
    difficulty: 'beginner',
  },
  {
    slug: 'data-connector',
    title: 'Data connector',
    description:
      'Stream rows from an external source into deck tables, charts, and reactive bindings.',
    time_estimate_min: 25,
    difficulty: 'intermediate',
  },
  {
    slug: 'export-format',
    title: 'Export format',
    description:
      'Add a new export target (PDF, SCORM, custom blob) with a streaming encoder pipeline.',
    time_estimate_min: 20,
    difficulty: 'advanced',
  },
];

export const PUBLISH_STEPS: ReadonlyArray<PublishStep> = [
  {
    step: 1,
    title: 'Develop',
    description:
      'Scaffold locally, implement the plugin interface, and iterate against the editor preview.',
  },
  {
    step: 2,
    title: 'Test',
    description:
      'Run the SDK test harness, run end-to-end smoke tests, and verify on a representative deck.',
  },
  {
    step: 3,
    title: 'Submit',
    description:
      'Push a tagged release, fill out the marketplace listing, and submit for review.',
  },
  {
    step: 4,
    title: 'Review',
    description:
      'Domio reviewers run security and policy checks, request changes if needed, and approve.',
  },
  {
    step: 5,
    title: 'Live',
    description:
      'Once approved, the plugin is published to the marketplace and available to all users.',
  },
];

export const SAMPLE_PLUGIN_REPO_URL = 'https://github.com/domio/plugin-template';

/**
 * Resolves the browser-friendly ZIP download URL for the sample plugin
 * repo. The archive is generated by the docs site pipeline and cached
 * on the marketing CDN.
 */
export const SAMPLE_PLUGIN_ZIP_URL = `${SAMPLE_PLUGIN_REPO_URL}/archive/refs/heads/main.zip`;

/**
 * Used by the Quickstart component to render copy-friendly code
 * snippets. Centralised here so the page and the tutorial anchor
 * sections stay in sync if the scaffold command ever changes.
 */
export const QUICKSTART_SNIPPETS = {
  install: 'npm install -g @domio/plugin-cli',
  scaffold: 'domio plugin init my-plugin --template=canvas-node',
  implement: [
    "import { definePlugin } from '@domio/plugin-sdk';",
    '',
    'export default definePlugin({',
    '  id: "my-plugin",',
    '  version: "0.1.0",',
    '  activate(ctx) {',
    '    ctx.canvas.registerNode({',
    '      type: "my-node",',
    '      geometry: () => import("./geometry"),',
    '      controls: () => import("./controls"),',
    '    });',
    '  },',
    '});',
  ].join('\n'),
  test: 'domio plugin dev --open',
  publish: 'domio plugin publish --review',
} as const;
