#!/usr/bin/env bash
#
# Phase 22-beta G1-8 — run-n-plus-one-audit.sh
#
# Fetches the OTel trace export from staging for the past hour, runs
# the N+1 detector, and emits a markdown report to
# `services/obs-control-plane/reports/n-plus-one/<date>.md`.
#
# Usage:
#   services/obs-control-plane/scripts/run-n-plus-one-audit.sh \
#     --otel-endpoint=https://otel.staging.domio.app/v1/traces \
#     --since=1h
#
# Prerequisites:
#   - jq, curl in PATH
#   - OTEL_API_TOKEN set (or passed via --token=)
#   - jq filter 'resourceSpans[].scopeSpans[].spans[]' applied

set -euo pipefail

ENDPOINT=""
TOKEN=""
SINCE="1h"
REPORT_DIR="services/obs-control-plane/reports/n-plus-one"
TODAY=$(date -u +%Y-%m-%d)
REPORT="$REPORT_DIR/$TODAY.md"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --otel-endpoint=*) ENDPOINT="${1#*=}" ;;
    --token=*) TOKEN="${1#*=}" ;;
    --since=*) SINCE="${1#*=}" ;;
    *) echo "unknown arg: $1" >&2; exit 2 ;;
  esac
  shift
done

if [[ -z "$ENDPOINT" || -z "$TOKEN" ]]; then
  echo "--otel-endpoint= and --token= are required" >&2
  exit 2
fi

mkdir -p "$REPORT_DIR"

# Fetch trace export. The endpoint MUST accept a `since` query param
# and return JSON in the standard OTel-JSON shape.
trace_json=$(mktemp)
http_code=$(curl -sS -o "$trace_json" -w "%{http_code}" \
  -H "Authorization: Bearer $TOKEN" \
  --data-urlencode "since=$SINCE" \
  "$ENDPOINT" || true)
if [[ "$http_code" != "200" ]]; then
  echo "otel endpoint returned $http_code" >&2
  cat "$trace_json" >&2
  exit 1
fi

# Pipe the trace through the detector. We use the `tsx` runner so
# TypeScript imports resolve cleanly.
detector_out=$(mktemp)
pnpm exec tsx --tsconfig services/obs-control-plane/tsconfig.json \
  services/obs-control-plane/src/cli/n_plus_one_audit.ts \
  < "$trace_json" > "$detector_out"

# Parse JSON and render markdown.
spans=$(jq -r '.spansAnalysed' "$detector_out")
findings=$(jq -r '.findings | length' "$detector_out")
high_fanout=$(jq -r '.highFanoutParents | length' "$detector_out")
pass=$(jq -r '.pass' "$detector_out")

cat > "$REPORT" <<HEADER
# N+1 Query Audit — $TODAY

Window: $SINCE
Spans analysed: $spans
N+1 findings: $findings
High-fanout parents: $high_fanout
Status: $([[ "$pass" == "true" ]] && echo PASS || echo FAIL)

## N+1 findings

| Parent | DB | Collection | Hash | Repeat | Distinct args | Sample span IDs |
|--------|----|------------|------|--------|---------------|------------------|
HEADER

jq -r '.findings[] | "| \(.parentName) | \(.dbSystem) | \(.dbCollection) | \(.statementHash) | \(.repeatCount) | \(.distinctArgs) | \(.sampleChildSpanIds | join(", ")) |"' "$detector_out" >> "$REPORT"

echo "" >> "$REPORT"
echo "## High-fanout parents" >> "$REPORT"
echo "" >> "$REPORT"
echo "| Parent | Child count |" >> "$REPORT"
echo "|--------|-------------|" >> "$REPORT"
jq -r '.highFanoutParents[] | "| \(.parentName) | \(.childCount) |"' "$detector_out" >> "$REPORT"

echo "" >> "$REPORT"
echo "_Generated by \`services/obs-control-plane/scripts/run-n-plus-one-audit.sh\`._" >> "$REPORT"

rm -f "$trace_json" "$detector_out"

if [[ "$pass" != "true" ]]; then
  echo "audit FAILED — see $REPORT" >&2
  exit 1
fi
echo "audit OK — $REPORT"