#!/usr/bin/env bash
#
# Phase 22-beta G1-6 — verify_hot_query_plans.sh
#
# Runs EXPLAIN (ANALYZE, BUFFERS) on each of the top-20 hot queries
# from `docs/05-data-database-design.md` §5.15.1 and writes a
# markdown report. Fails CI if any plan shows a `Seq Scan` on a
# table > 100k rows, or if any query exceeds its budgeted runtime.
#
# Usage:
#   infra/db/scripts/verify_hot_query_plans.sh \
#     --profile=staging \
#     --rows-per-table=1000000
#
# Prerequisites:
#   - psql in PATH
#   - DATABASE_URL set (or use --profile=staging to pull from
#     ~/.domio/staging.env)
#
# Output:
#   docs/05-data-database-design/query-plans/<date>.md

set -euo pipefail

PROFILE=""
ROWS_PER_TABLE=1000000
REPORT_DIR="docs/05-data-database-design/query-plans"
TODAY=$(date -u +%Y-%m-%d)
REPORT="$REPORT_DIR/$TODAY.md"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --profile=*) PROFILE="${1#*=}" ;;
    --rows-per-table=*) ROWS_PER_TABLE="${1#*=}" ;;
    --report-dir=*) REPORT_DIR="${1#*=}" ;;
    *) echo "unknown arg: $1" >&2; exit 2 ;;
  esac
  shift
done

if [[ -n "$PROFILE" ]]; then
  ENV_FILE="$HOME/.domio/$PROFILE.env"
  if [[ ! -f "$ENV_FILE" ]]; then
    echo "profile env file missing: $ENV_FILE" >&2
    exit 1
  fi
  # shellcheck disable=SC1090
  source "$ENV_FILE"
fi

if [[ -z "${DATABASE_URL:-}" ]]; then
  echo "DATABASE_URL must be set" >&2
  exit 1
fi

mkdir -p "$REPORT_DIR"

cat > "$REPORT" <<HEADER
# Hot-Query Plan Verification — $TODAY

Profile: \`${PROFILE:-local}\`
Rows per table: $ROWS_PER_TABLE

| # | Query | Plan | Latency | Status |
|---|-------|------|---------|--------|
HEADER

declare -a QUERIES=(
  "select * from comments where deck_id=\$1 and parent_id is null order by created_at desc limit 50"
  "select * from comments where deck_id=\$1 and parent_id=\$2 order by created_at asc"
  "select * from assignments where assignee_id=\$1 and status='open' order by due_at asc limit 100"
  "select count(*) from approval_requests where deck_id=\$1 and status='pending'"
  "select * from slides where deck_id=\$1 order by position asc"
  "select * from elements where slide_id=\$1"
  "select * from decks where workspace_id=\$1 and deleted_at is null order by updated_at desc limit 50"
  "select count(*) from decks where workspace_id=\$1 and created_at > now() - interval '7 days'"
  "select * from share_links where deck_id=\$1 and expires_at > now()"
  "select * from audit_events where workspace_id=\$1 and occurred_at > \$2 order by occurred_at desc limit 100"
  "select * from sessions where id=\$1 for update"
  "update sessions set version=version+1, ... where id=\$1 and version=\$2"
  "select bucket, count(*) from events_aggregated where tenant_id=\$1 and bucket > \$2 group by bucket"
  "select * from library_items where workspace_id=\$1 and kind=\$2 order by created_at desc limit 50"
  "select * from notifications where recipient_id=\$1 and read_at is null order by created_at desc limit 50"
  "select * from merge_requests where target_deck_id=\$1 and status='open'"
  "select * from share_links where token=\$1"
  "select * from presence where deck_id=\$1 and last_seen > now() - interval '30 seconds'"
  "select count(*) from events_raw where occurred_at > now() - interval '5 minutes'"
  "select * from audit_events where workspace_id=\$1 and kind='login' order by occurred_at desc limit 100"
)

# Bind dummy params. We're testing plan shape, not result correctness.
BIND_ARGS=(-v ON_ERROR_STOP=1 --quiet --pset footer=off)

FAIL=0
for i in "${!QUERIES[@]}"; do
  Q="${QUERIES[$i]}"
  # Replace $1/$2 with literal placeholders that won't error on plan.
  SAFE=$(echo "$Q" | sed -e 's/\$1/'"'00000000-0000-0000-0000-000000000000'"'/g' \
                          -e 's/\$2/'"'00000000-0000-0000-0000-000000000001'"'/g' \
                          -e "s/\$2/now() - interval '1 day'/g")
  OUT=$(psql "${BIND_ARGS[@]}" -c "EXPLAIN (ANALYZE, BUFFERS) $SAFE" "$DATABASE_URL" 2>&1 || true)
  PLAN_TYPE=$(echo "$OUT" | grep -Eo "Index Scan|Index Only Scan|Seq Scan|Bitmap Heap Scan" | head -1)
  LATENCY=$(echo "$OUT" | grep -Eo "Execution Time: [0-9]+\.[0-9]+ ms" | head -1)
  STATUS="OK"
  if [[ "$PLAN_TYPE" == "Seq Scan" ]]; then
    STATUS="FAIL: Seq Scan"
    FAIL=1
  fi
  if [[ -z "$PLAN_TYPE" ]]; then
    STATUS="FAIL: no plan"
    FAIL=1
  fi
  printf "| %d | %s | %s | %s | %s |\n" $((i + 1)) "${Q:0:60}..." "${PLAN_TYPE:-?}" "${LATENCY:-?}" "$STATUS" >> "$REPORT"
done

echo "" >> "$REPORT"
echo "_Generated by \`infra/db/scripts/verify_hot_query_plans.sh\`._" >> "$REPORT"

if [[ $FAIL -ne 0 ]]; then
  echo "verification FAILED — see $REPORT" >&2
  exit 1
fi

echo "verification OK — $REPORT"
