/**
 * @domio/audience-service — shared types.
 *
 * Phase 16 W1. These types are referenced by every audience engine.
 * They model the participant identity, the cross-shard session
 * coordinate, and the bundle envelope emitted when a participant
 * joins a session.
 */

/** Stable, opaque participant id. Generated by the gateway at
 *  handshake time and pinned to the browser fingerprint. */
export type ParticipantId = string & { readonly __brand: 'ParticipantId' };

/** Session code as generated by @domio/session-code. */
export type SessionCode = string & { readonly __brand: 'SessionCode' };

/** Composite key used by audience-engine stores. The shard index
 *  comes from the session code; participants on the same code always
 *  route to the same shard. */
export interface ShardCoordinate {
  readonly session_code: SessionCode;
  readonly shard_index: number;
}

export type ParticipantLocale = 'en' | 'bn' | 'es' | string;

/** Bundle returned to the participant after `POST /v1/audience/join`.
 *  The audience_widgets surface in the join-web PWA renders widgets
 *  from this bundle; the audience_session_id is reused for every
 *  follow-up call so the WS gateway can index state. */
export interface AudienceJoinBundle {
  readonly audience_session_id: string;
  readonly participant_id: ParticipantId;
  readonly session_metadata: AudienceSessionMetadata;
  readonly widgets: ReadonlyArray<AudienceWidgetDescriptor>;
  /** HLC anchor for clock skew on the client. */
  readonly server_ts_ms: number;
  /** Reconnect token; the audience PWA persists this in IndexedDB. */
  readonly reconnect_token: string;
}

export interface AudienceSessionMetadata {
  readonly session_id: string;
  readonly workspace_id: string;
  readonly title: string;
  readonly started_at: string;
  readonly presenter_display_name: string;
  readonly locale: ParticipantLocale;
  readonly reduced_motion: boolean;
}

/** Widget descriptor — published to the audience PWA on join. The
 *  payload is widget-type-specific (poll, quiz, qa, ...). */
export interface AudienceWidgetDescriptor {
  readonly widget_id: string;
  readonly type: AudienceWidgetType;
  readonly position: number;
  readonly payload: Record<string, unknown>;
  readonly updated_at_ms: number;
}

export type AudienceWidgetType =
  | 'poll'
  | 'word_cloud'
  | 'qa'
  | 'quiz'
  | 'reaction'
  | 'nav_vote'
  | 'sentiment'
  | 'raise_hand';

export function participantId(value: string): ParticipantId {
  return value as ParticipantId;
}

export function sessionCode(value: string): SessionCode {
  return value as SessionCode;
}

/** Canonical snapshot emitted when a participant joins a presenter
 *  session. The participant service resolves this from the
 *  presenter-service via PresenterLookup; the join-web PWA renders
 *  the session title + current slide from this bundle. */
export interface AudienceSnapshot {
  readonly session_id: string;
  readonly ended_at: string | null;
  readonly current_slide_id: string | null;
  readonly presenter_display_name: string;
  readonly title: string;
}
