name: setup-go

on:
  workflow_call:
    inputs:
      go-version:
        description: Go version (must match .tool-versions).
        type: string
        default: '1.23.4'
      cache:
        description: Enable Go module cache.
        type: boolean
        default: true

jobs:
  main:
    name: setup-go
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v5.2.0
        with:
          go-version: ${{ inputs.go-version }}
          cache: ${{ inputs.cache }}

      - name: Verify go.mod
        run: go mod download && go mod verify
        shell: bash
